library(here)
library(stringr)
library(ggplot2)
library(gridExtra)

# Clear the current workspace and set the working directory
rm(list=ls())
#setwd(here("mapmatching-project"))

fullData <- read.csv("Results/full_data.csv")

print("-----------------")
print("ALGORITHM RESULTS")
print("-----------------")
algorithmAccuracy <- aov(accuracy ~ algorithm, data = fullData)
print(summary(algorithmAccuracy))
algorithmMissed <- aov(missed ~ algorithm, data = fullData)
print(summary(algorithmMissed))
algorithmFalse <- aov(false ~ algorithm, data = fullData)
print(summary(algorithmFalse))
algorithmTime <- aov(time ~ algorithm, data = fullData)
print(summary(algorithmTime))
# 
# print("-------------")
# print("PHONE RESULTS")
# print("-------------")
# phoneAccuracy <- aov(accuracy ~ phone, data = fullData)
# print(summary(phoneAccuracy))
# phoneMissed <- aov(missed ~ phone, data = fullData)
# print(summary(phoneMissed))
# phoneFalse <- aov(false ~ phone, data = fullData)
# print(summary(phoneFalse))
# phoneTime <- aov(time ~ phone, data = fullData)
# print(summary(phoneTime))
# 
# print("----------------")
# print("SCENARIO RESULTS")
# print("----------------")
# scenarioAccuracy <- aov(accuracy ~ scenario, data = fullData)
# print(summary(scenarioAccuracy))
# scenarioMissed <- aov(missed ~ scenario, data = fullData)
# print(summary(scenarioMissed))
# scenarioFalse <- aov(false ~ scenario, data = fullData)
# print(summary(scenarioFalse))
# scenarioTime <- aov(time ~ scenario, data = fullData)
# print(summary(scenarioTime))
# 
# print("-------------------")
# print("APPLICATION RESULTS")
# print("-------------------")
# applicationAccuracy <- aov(accuracy ~ application, data = fullData)
# print(summary(applicationAccuracy))
# applicationMissed <- aov(missed ~ application, data = fullData)
# print(summary(applicationMissed))
# applicationFalse <- aov(false ~ application, data = fullData)
# print(summary(applicationFalse))
# applicationTime <- aov(time ~ application, data = fullData)
# print(summary(applicationTime))
# 
# print("-------------------------")
# print("ALGORITHM X PHONE RESULTS")
# print("-------------------------")
# algoPHONEAccuracy <- aov(accuracy ~ algorithm*phone, data = fullData)
# print(summary(algoPHONEAccuracy))
# algoPHONEMissed <- aov(missed ~ algorithm*phone, data = fullData)
# print(summary(algoPHONEMissed))
# algoPHONEFalse <- aov(false ~ algorithm*phone, data = fullData)
# print(summary(algoPHONEFalse))
# algoPHONETime <- aov(time ~ algorithm*phone, data = fullData)
# print(summary(algoPHONETime))
# 
# print("----------------------------")
# print("ALGORITHM X SCENARIO RESULTS")
# print("----------------------------")
# algoScenAccuracy <- aov(accuracy ~ algorithm*scenario, data = fullData)
# print(summary(algoScenAccuracy))
# algoScenMissed <- aov(missed ~ algorithm*scenario, data = fullData)
# print(summary(algoScenMissed))
# algoScenFalse <- aov(false ~ algorithm*scenario, data = fullData)
# print(summary(algoScenFalse))
# algoScenTime <- aov(time ~ algorithm*scenario, data = fullData)
# print(summary(algoScenTime))
# 
# print("-------------------------------")
# print("ALGORITHM X APPLICATION RESULTS")
# print("-------------------------------")
# algoAPPAccuracy <- aov(accuracy ~ algorithm*application, data = fullData)
# print(summary(algoAPPAccuracy))
# algoAPPMissed <- aov(missed ~ algorithm*application, data = fullData)
# print(summary(algoAPPMissed))
# algoAPPFalse <- aov(false ~ algorithm*application, data = fullData)
# print(summary(algoAPPFalse))
# algoAPPTime <- aov(time ~ algorithm*application, data = fullData)
# print(summary(algoAPPTime))